This is makeindex, version 2.16 [TeX Live 2022] (kpathsea + Thai support).
Scanning style file ./example.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file example.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (9 comparisons).
Generating output file example.acr....done (14 lines written, 0 warnings).
Output written in example.acr.
Transcript written in example.alg.
